# Site settings
title: The website of Alice Bartlett
email: alice.bartlett@gmail.com
description: The home of typing by Alice Bartlett ğŸ‘©ğŸ»â€ğŸ’»
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://alicebartlett.co.uk" # the base hostname & protocol for your site
twitter_username: alicebartlett
github_username:  alicebartlett

# Build settings
markdown: kramdown

permalink: /blog/:title

feed:
  categories:
    - sewing
    - weaknotes
    - yearnotes
